if(DEFINED SWIG_WRAP_LANG)
    MESSAGE(STATUS "SWIG_WRAP_LANG ${SWIG_WRAP_LANG}")
    set(SWIG_TARGET_NAME ${PROJECT_NAME}-${SWIG_WRAP_LANG}-swig-static)
    MESSAGE(STATUS "SWIG_TARGET_NAME ${SWIG_TARGET_NAME}")

    set(CMAKE_SWIG_OUTDIR "${CMAKE_BINARY_DIR}/swig/${SWIG_WRAP_LANG}/${CMAKE_SYSTEM_NAME}")
    set(SWIG_OUTFILE_DIR "${CMAKE_BINARY_DIR}/swig/${SWIG_WRAP_LANG}/${CMAKE_SYSTEM_NAME}")

    list(APPEND CMAKE_SWIG_FLAGS "-includeall")
    # list(APPEND CMAKE_SWIG_FLAGS "-fcompact")
    list(APPEND CMAKE_SWIG_FLAGS "-fvirtual")
    list(APPEND CMAKE_SWIG_FLAGS "-v")
    list(APPEND CMAKE_SWIG_FLAGS "-w201")
    list(APPEND CMAKE_SWIG_FLAGS "-w312")
    list(APPEND CMAKE_SWIG_FLAGS "-ignoremissing")
    # list(APPEND CMAKE_SWIG_FLAGS "-cpperraswarn")
    # list(APPEND CMAKE_SWIG_FLAGS "-DSWIG_TYPE_TABLE=myprojectname")

    set(SWIG_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/swig.in")

    MESSAGE(STATUS "CMAKE_SWIG_FLAGS ${CMAKE_SWIG_FLAGS}")

    set_property(SOURCE "${SWIG_INCLUDE_DIR}/swig.i" PROPERTY INCLUDE_DIRECTORIES ${SWIG_WRAP_INCLUDE})
    set_property(SOURCE "${SWIG_INCLUDE_DIR}/swig.i" PROPERTY CPLUSPLUS ON)
    set_property(SOURCE "${SWIG_INCLUDE_DIR}/swig.i" PROPERTY SWIG_MODULE_NAME ${PROJECT_NAME})

    # MESSAGE(STATUS "SWIG_SOURCE_FILES ${SWIG_SOURCE_FILES}")

    SWIG_ADD_LIBRARY(${SWIG_TARGET_NAME}
        TYPE STATIC
        LANGUAGE ${SWIG_WRAP_LANG}
        SOURCES ${SWIG_INCLUDE_DIR}/swig.i
        )

    MESSAGE(STATUS "SWIG_MODULE_${PROJECT_NAME}_REAL_NAME ${SWIG_MODULE_${PROJECT_NAME}_REAL_NAME}")

endif()

