set(SWIG_WRAP_LANG "ruby")
string(TOUPPER ${SWIG_WRAP_LANG} SWIG_WRAP_LANG_UPPER)

find_package( Ruby REQUIRED )

if (RUBY_FOUND)
    message(STATUS "RUBY_EXECUTABLE ${RUBY_EXECUTABLE}")
    message(STATUS "RUBY_INCLUDE_DIRS ${RUBY_INCLUDE_DIRS}")
    message(STATUS "RUBY_LIBRARY ${RUBY_LIBRARY}")
    message(STATUS "RUBY_VERSION ${RUBY_VERSION}")
    message(STATUS "RUBY_FOUND ${RUBY_FOUND}")
    message(STATUS "RUBY_INCLUDE_PATH ${RUBY_INCLUDE_PATH}")

    list(APPEND EXTRA_LIBS ${RUBY_LIBRARY})

    list(APPEND SWIG_WRAP_INCLUDE ${RUBY_INCLUDE_DIRS})
    list(APPEND SWIG_WRAP_LIBRARIES ${RUBY_LIBRARY})
endif()
