
MACRO(SUBDIRLIST result curdir dirs)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
      LIST(APPEND dirlist ${child})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
  if(result)
    list(REMOVE_DUPLICATES result)
  endif()

  FOREACH(subdir ${dirlist})
    IF(IS_DIRECTORY ${curdir}/${subdir})
      LIST (APPEND ${dirs} "${curdir}/${subdir}")
    elseif(IS_DIRECTORY ${subdir})
      LIST (APPEND ${dirs} "${subdir}")
    ENDIF()
    SUBDIRLIST(result "${curdir}/${subdir}" ${dirs})
  ENDFOREACH()
ENDMACRO()
