# This is a basic workflow to help you get started with Actions

name: macOS-swig-lua

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: view home
      run: |
        ls .github
        pwd

    - uses: apple-actions/import-codesign-certs@v1
      with: 
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    
    - name: install swig
      run: brew install swig
    
    - name: install doxygen
      run: brew install doxygen
    
    - name: install graphviz
      run: brew install graphviz
      
    - name: build macOS
      run: |
        export GTEST_OUTPUT="xml"
        cmake --version
        cmake . -dgame_DOC:BOOL=ON  -dgame_TEST:BOOL=ON -DCMAKE_INSTALL_PREFIX=install -G "Xcode"
        cmake --build . --config Release --target package
        cd .build_macOS/src/platform/macos/test/cpp/Debug/game-test-static.app/Contents/MacOS/
        ./game-test-static
        
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          game*
          src/platform/macos/test/cpp/Debug/game-test-static.app/Contents/MacOS/test_detail.xml
