# This is a basic workflow to help you get started with Actions

name: macOS-swig-lua

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: install lua
      run: brew install lua
    
    - name: install swig
      run: brew install swig
      
    - name: print cmake version
      run: cmake --version
      
    - name: build macOS
      run: |
        cmake . -DCMAKE_INSTALL_PREFIX=install -G "Xcode"
        cmake --build . --config Release --target install
